version: "3.2"
services:
  ads-db-local:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_DB=ads-service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
